{
 "title": "New dashboard Copy",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Overall GET/PUT requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Latency Exceeded",
     "bucketAggs": [
      {
       "$$hashKey": "object:3116",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:3114",
       "field": "latency_exceeded",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Latency Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "alias": "Latency Exceeded",
     "bucketAggs": [
      {
       "$$hashKey": "object:3116",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:3114",
       "field": "latency_exceeded",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "latency_exceeded: 1",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Latency SLO Exceeded",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:92",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:90",
       "field": "latency_exceeded",
       "id": "1",
       "inlineScript": "_value * 10",
       "meta": {
        "max": true,
        "std_deviation_bounds_lower": false,
        "std_deviation_bounds_upper": false,
        "sum": false
       },
       "settings": { "script": { "inline": "_value * 10" } },
       "type": "extended_stats"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Overall Latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1072",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:2055",
       "field": "latency",
       "id": "3",
       "meta": {},
       "settings": {
        "percents": [
         25,
         50,
         75,
         95,
         99
        ]
       },
       "type": "percentiles"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Object Size Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "4KiB Read Latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1072",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:2055",
       "field": "latency",
       "id": "3",
       "meta": {},
       "settings": {
        "percents": [
         25,
         50,
         75,
         95,
         99
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "size_in_bytes: 4096 AND workload: read",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "4KiB Write Latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1072",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:2055",
       "field": "latency",
       "id": "3",
       "meta": {},
       "settings": {
        "percents": [
         25,
         50,
         75,
         95,
         99
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "size_in_bytes: 4096 AND workload: write",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "1MiB Read Latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1072",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:2055",
       "field": "latency",
       "id": "3",
       "meta": {},
       "settings": {
        "percents": [
         25,
         50,
         75,
         95,
         99
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "size_in_bytes: 1048576 AND workload: read",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "1MiB Write Latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1072",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:2055",
       "field": "latency",
       "id": "3",
       "meta": {},
       "settings": {
        "percents": [
         25,
         50,
         75,
         95,
         99
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "size_in_bytes: 1048576 AND workload: write",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "2MiB Read Latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1072",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:2055",
       "field": "latency",
       "id": "3",
       "meta": {},
       "settings": {
        "percents": [
         25,
         50,
         75,
         95,
         99
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "size_in_bytes: 2097152 AND workload: read",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "2MiB Write Latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1072",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:2055",
       "field": "latency",
       "id": "3",
       "meta": {},
       "settings": {
        "percents": [
         25,
         50,
         75,
         95,
         99
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "size_in_bytes: 2097152 AND workload: write",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "4MiB Read Latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1072",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:2055",
       "field": "latency",
       "id": "3",
       "meta": {},
       "settings": {
        "percents": [
         25,
         50,
         75,
         95,
         99
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "size_in_bytes: 4194304 AND workload: read",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "4MiB Write Latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1072",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:2055",
       "field": "latency",
       "id": "3",
       "meta": {},
       "settings": {
        "percents": [
         25,
         50,
         75,
         95,
         99
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "size_in_bytes: 4194304 AND workload: write",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}